### ISSUE TITLE
When you download bibtext file, it changes url to .../export

### ISSUE THREAD

**Issue by JaakkoLipsanen** [ScrumMestarit/BibTeXt#31]
Probably shouldn't do that

**Comment by anttilip** [comment]
I can't see any trivial fix for this. Since view is run on client, it can't directly call backend methods. It has to use proper requests like now `get '/:page_id/export', to: 'pages#export`. And because `pages#export` uses `send_data`, which is a response, it can't even redirect or render any other page.

**Comment by anttilip** [comment]
> [..] but it seems like overkill for this issue.

Still did it. No regrets.
